require 'rubygems'
require 'fileutils'

namespace :fw do
  desc "Install" 
  task :install do
    %w[/etc/fw /etc/fw/rules.enabled /etc/fw/rules.available].each do |p|
      unless File.exist? p
        FileUtils.mkdir p
      end
    end

    Dir["example-rules/*.rule"].each do |rule|
      dest = "/etc/fw/rules.available/#{rule}"
      unless File.exist? dest
        FileUtils.cp rule, dest
      end
    end


    unless File.exist? "/etc/fw/.set-rules"
      system "touch", "/etc/fw/.set-rules"
    end

    %w[bin/fwcntl].each do |f|
      fname = File.basename(f)
      FileUtils.cp f, "/etc/fw/#{fname}"
    end

    FileUtils.cp "files/fw.crontab", "/etc/cron.d"
  end
end
